replicaCount: 1
namespace: helm
image:
  repository: locornermsacrdev.azurecr.io/logcorner.edusync.speech.command
  tag: "1096"
imagePullPolicy: IfNotPresent
restartPolicy: Always
service:
  type: LoadBalancer #ClusterIP
  port: 80
  targetPort: 80
  ssl_port: 443
  ssl_targetPort: 443
ingress:
  host: helm.kubernetes.docker.com
  secretName: logcorner-ingress-tls
