replicaCount: 1

image:
  repository: datasynchroacr.azurecr.io/web-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer  # ClusterIP
  port: 80
  targetPort: 5000  
  containerPort: 5000

env:
  title: "Welcome to Azure Kubernetes Service (AKS)"
  aspnetcoreEnvironment: "Kubernetes"

configMapRef:
  sqlServerKey: SQL_SERVER
  dbNameKey: DB_NAME
  userNameKey: USER_NAME

secretRef:
  dbPasswordKey: DB_PASSWORD

connectionStringTemplate: "Data Source=$(SQL_SERVER);Initial Catalog=$(DB_NAME);User=$(USER_NAME);Password=$(DB_PASSWORD)"


configMap:
  name: mssql-config
  labels:
    product: mssql
  data:
    SQL_SERVER: "sqlserver-datasynchro.database.windows.net"
    DB_NAME: "WeatherForecastDb" #"LogCorner.EduSync.Speech.Database"
    USER_NAME: "logcorner"
secret:
  name: mssql
  labels:
    version: "1.0.0"
    product: "mssql"
  data:
    DB_PASSWORD: "MySecureP@ssword"  # Sensitive data can be overridden securely during deployment
