apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 282d601e-33ea-48d0-8dd7-19e7f218cc2c #$workloadManagedIdentityClientId => workload-managed-identity-datasynchro
    azure.workload.identity/tenant-id: f12a747a-cddf-4426-96ff-ebe055e215a3 # $tenantId
  labels:
    azure.workload.identity/use: "true"
  name: alb-controller-sa
  namespace: azure-alb-system