apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend-app
  namespace: azure-resources
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: web-frontend-app
          image: datasynchroacr.azurecr.io/web-app:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5000
            - name: ASPNETCORE_ENVIRONMENT
              value: Kubernetes
            - name: WEBAPI_COMMAND_URL
              value : http://webapi-service
            - name: WEBAPI_QUERY_URL
              value : http://web-api-query-service
            - name: HubUrl
              value : http://signalr-service

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: azure-resources
  labels:
    app: webapp

spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer #ClusterIP