# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: SECRETS

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Checking if chart path exists..."
            $chartPath = "$(System.DefaultWorkingDirectory)/iac/scripts"
      
            if (Test-Path -Path $chartPath -PathType Container) {
                Write-Host "Chart path exists."
                ls
            } else {
                Write-Host "Chart path does not exist."
            }
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'BICEP-SP'
    ScriptType: 'FilePath'
    ScriptPath: '$(System.DefaultWorkingDirectory)/iac/scripts/certificate.ps1'
    ScriptArguments: '-pfxPassword $(ConvertTo-SecureString $(pfxPassword) -AsPlainText -Force)'
    azurePowerShellVersion: 'LatestVersion'
