# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- name: repository
  value: locornermsacrdev
- name: imageName
  value: logcorner.edusync.speech.command
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Docker@2
  enabled: true
  displayName: Docker Build
  inputs:
    repository: '$(repository)'
    command: 'build'
    Dockerfile: '/**/LogCorner.EduSync.Speech.Presentation/Dockerfile'
    arguments: '-t $(repository).azurecr.io/$(imageName):$(Build.BuildId)'
- task: AzureCLI@2
  enabled: false
  displayName: Docker Push
  inputs:
    azureSubscription:  ${{ variables.serviceConnectionName }}
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      accessToken=$(az acr login --name $(repository) --expose-token --output tsv --query accessToken)
      echo $accessToken | docker login $(repository).azurecr.io --username 00000000-0000-0000-0000-000000000000 --password-stdin
      docker push $(repository).azurecr.io/$(imageName):$(Build.BuildId)