FROM mcr.microsoft.com/powershell:alpine-3.14
RUN apk update && apk add bash
RUN bash
RUN apk add --no-cache wget
RUN pwsh -c "&{Install-Module -Name Az -AllowClobber -Scope AllUsers -Force}"
RUN pwsh -c "&{ Install-Module Az.Accounts, Az.KeyVault, Az.Resources,  AzureRM.Profile, Az.Storage, Posh-ACME -Force }"
RUN apk add libc6-compat
RUN wget https://azcopyvnext.azureedge.net/release20190301/azcopy_linux_amd64_10.0.8.tar.gz && tar xvzf ./azcopy_linux_amd64_10.0.8.tar.gz && rm ./azcopy_linux_amd64_10.0.8.tar.gz && cp ./azcopy_linux_amd64_10.0.8/azcopy ./ && rm -rf ./azcopy_linux_amd64_10.0.8 && ./azcopy --version

RUN mkdir app
COPY . app/
WORKDIR /app
ENTRYPOINT ["pwsh","run.ps1"]