# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: hello-world-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"
#     nginx.ingress.kubernetes.io/use-regex: "true"
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
# spec:
#   ingressClassName: nginx
#   tls:
#   - hosts:
#     - ingress.cloud-devops-craft.com
#     secretName: ingress-tls-csi
#   rules:
#   - host: demo.azure.com
#     http:
#       paths:
#       - path: /aks-command-api(/|$)(.*)
#         pathType: Prefix
#         backend:
#           service:
#             name: logcorner-command-http-api-service
#             port:
#               number: 80
#       - path: /hello-world-one(/|$)(.*)
#         pathType: Prefix
#         backend:
#           service:
#             name: aks-helloworld-one
#             port:
#               number: 80
#       - path: /hello-world-two(/|$)(.*)
#         pathType: Prefix
#         backend:
#           service:
#             name: aks-helloworld-two
#             port:
#               number: 80
#       - path: /(.*)
#         pathType: Prefix
#         backend:
#           service:
#             name: aks-helloworld-one
#             port:
#               number: 80
# # https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-nginx-tls