# templates/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    {{- range $key, $value := .Values.configMap.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
data:
  SQL_SERVER: {{ .Values.configMap.data.SQL_SERVER | quote }}
  DB_NAME: {{ .Values.configMap.data.DB_NAME | quote }}
  USER_NAME: {{ .Values.configMap.data.USER_NAME | quote }}
