apiVersion: v1
kind: Secret
metadata:
  name: mssql
  namespace: helm
  labels:
    version: 1.0.0
    product: mssql
stringData:
  ConnectionStrings__SpeechDB: "Data Source=mssql-server-edusync-dev.database.windows.net;Initial Catalog=backend-db-edusync-dev;User=mssql-admin-user;Password=fwZTfA?JrBVh{6jJPDk+"
