# templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: default
  labels:
    {{- range $key, $value := .Values.secret.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
stringData:
  DB_PASSWORD: {{ .Values.secret.data.DB_PASSWORD | quote }}
