# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- name: repository
  value: locornermsacrdev
- name: imageName
  value: logcorner.edusync.speech.command
- name: serviceConnectionName
  value: 'BICEP-SP'
- name: sqlServerName
  value: 'mssql-server-edusync-dev.database.windows.net'

- name: sqlDatabaseName
  value: 'backend-db-edusync-dev'
  
- name: sqlScriptPath
  value: 'script.sql'

- name : secretValue
  value: 'P@ssw0rd'
  
- name : administratorLogin
  value: 'logcorner'

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Checking if chart path exists..."
      ls -al $(System.DefaultWorkingDirectory)/iac/helm-chart/chart/logcorner.edusync.speech
      if [ -d "$(System.DefaultWorkingDirectory)/iac/helm-chart/chart/logcorner.edusync.speech" ]; then
        echo "Chart path exists."
      else
        echo "Chart path does not exist."
      fi


- task: Docker@2
  enabled: true
  displayName: Docker Build
  inputs:
    repository: '$(repository)'
    command: 'build'
    Dockerfile: '/**/LogCorner.EduSync.Speech.Presentation/Dockerfile'
    buildContext: 'src'
    arguments: '-t $(repository).azurecr.io/$(imageName):$(Build.BuildId)'
- task: AzureCLI@2
  enabled: true
  displayName: Docker Push
  inputs:
    azureSubscription: $(serviceConnectionName)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      accessToken=$(az acr login --name $(repository) --expose-token --output tsv --query accessToken)
      echo $accessToken | docker login $(repository).azurecr.io --username 00000000-0000-0000-0000-000000000000 --password-stdin
      docker push $(repository).azurecr.io/$(imageName):$(Build.BuildId)
- task: HelmDeploy@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: $(serviceConnectionName)
    azureResourceGroup: 'rg-edusync-dev'
    kubernetesCluster: 'aks-edusync-dev'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: '$(System.DefaultWorkingDirectory)/iac/helm-chart/chart/logcorner.edusync.speech'
    chartVersion: '1.0.1'
    releaseName: 'logcorner-command'
    
- task: SqlAzureDacpacDeployment@1
  enabled: true
  inputs:
    azureSubscription: $(serviceConnectionName)
    ServerName: $(sqlServerName)
    DatabaseName: $(sqlDatabaseName)
    SqlUsername: $(administratorLogin)
    SqlPassword: $(secretValue)
    deployType: 'SqlTask'
    sqlFile: $(Build.Repository.LocalPath)\data\$(sqlScriptPath)