name: Deploy-Azure-Common

trigger: none

variables: 

- name: azureResourceManagerConnection
  value: 'BICEP-SP'

- name: resourceGroupName
  value: RG_END_TO_END_DATA_ENGINEERING_PROJECT

- name: sqlServerName
  value: 'mssql-server-edusync-dev.database.windows.net'

- name: sqlDatabaseName
  value: 'backend-db-edusync-dev'

- group: DB_VARIABLES_SECRETS


pool:
  vmImage: windows-latest
stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - job: Build
      displayName: Build code and database
      steps:
      - checkout: self
      - task: DotNetCoreCLI@2
        displayName: dotnet restore
        enabled: false
        inputs:
          command: restore
          projects: '**/*.csproj'
      - task: DotNetCoreCLI@2
        displayName: dotnet build
        enabled: false
        inputs:
          projects: '**/*.csproj'
      - task: VSBuild@1
        displayName: database build
        inputs:
          solution: '**\*.sqlproj'
      - task: DotNetCoreCLI@2
        displayName: dotnet test
        enabled: false
        inputs:
          command: test
          projects: '**/*Unit[Tt]ests/*.csproj'
      - task: DotNetCoreCLI@2
        displayName: dotnet collect code coverage
        enabled: false
        inputs:
          command: test
          projects: '**/*[Uu]nit[Tt]ests/*.csproj'
          arguments: '--collect "Code Coverage"'
      - task: PublishCodeCoverageResults@1
        enabled: false
        displayName: Publish code coverage results
        inputs:
          codeCoverageTool: 'Cobertura'
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*.cobertura.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/_temp/cchtml'
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)/src/LogCorner.EduSync.Speech.Database/bin/Debug'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'DatabaseCode'
          publishLocation: 'Container'
      

- stage: Deploy
  displayName: Deploy Stage
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy Job
    pool:
      vmImage: windows-latest
    steps:
    - checkout: self    
    - download: current
      artifact: DatabaseCode

    - task: DownloadPipelineArtifact@2
      enabled: false
      inputs:
        artifactName: 'DatabaseCode'
        targetPath: $(Build.SourcesDirectory)/FunctionAppCode

    - task: SqlAzureDacpacDeployment@1
      enabled: true
      inputs:
        azureSubscription: '$(azureResourceManagerConnection)'
        AuthenticationType: 'server'
        ServerName: '$(sqlServerName)'
        DatabaseName: '$(sqlDatabaseName)'
        SqlUsername: 'mssql-admin-user'
        SqlPassword: '$(SqlServer--Password)'
        deployType: 'DacpacTask'
        DeploymentAction: 'Publish'
        DacpacFile: '$(Pipeline.Workspace)/DatabaseCode/LogCorner.EduSync.Speech.Database.dacpac'
        IpDetectionMethod: 'AutoDetect'