apiVersion: v2
name: service-broker
appVersion: "1.0.0"
description: A Helm chart for the service broker of the speech command API in logcorner edusync speech microservice architecture 1.0.0
version: 1.0.0
type: application
