apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-01
  namespace: azure-workloads
  annotations:
    alb.networking.azure.io/alb-id: /subscriptions/023b2039-5c23-44b8-844e-c002f8ed431d/resourceGroups/RG-EVENT-DRIVEN-ARCHITECTURE/providers/Microsoft.ServiceNetworking/trafficControllers/appgwforcon-datasynchro
spec:
  gatewayClassName: azure-alb-external
  listeners:
  - name: https-listener
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind : Secret
        group: ""
        name: logcorner-datasync-cert
  addresses:
  - type: alb.networking.azure.io/alb-frontend
    value: datasynchro-frontend
---


---

---

---
