apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-app
  namespace: azure-resources
  labels:
    app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-sa
      containers:
        - name: broker-app
          image: datasynchroacr.azurecr.io/broker-app:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
          
            - name: DOTNET_ENVIRONMENT
              value: Kubernetes
            - name: ServiceBusNamespace
              value: sb-namespace-datasynchro.servicebus.windows.net
            - name: ServiceBusQueueName
              value: sb-queue-datasynchro
            - name: HubUrl
              value: http://signalr-service/logcornerhub
            - name: AzureCosmosDB__ConnectionString
              value: AccountEndpoint=https://cosmos-datasynchro-002.documents.azure.com:443/;AccountKey=h7MMLPGa5dEVdccvaq9CoiBhVMPGGSKsyeckXbrNc6QLTLEWA0vAcvsSpYHDnLCf6jwUjo4XYlXGACDbjoozFQ==;

---
apiVersion: v1
kind: Service
metadata:
  name: broker-service
  namespace: azure-resources
  labels:
    app: broker

spec:
  selector:
    app: broker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP