
apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-config
  namespace: azure-workloads
  labels:
    app: web-api-command-app
data:
  SQL_SERVER: "sqlserver-datasynchro.database.windows.net"
  DB_NAME: "LogCorner.EduSync.Speech.Database"
  USER_NAME: "logcorner"
---
apiVersion: v1
kind: Secret
metadata:
  name: mssql
  namespace: azure-workloads
  labels:
    app: web-api-command-app
stringData:
  DB_PASSWORD: MySecureP@ssword
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-command
  namespace: azure-workloads
  labels:
    app: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-sa
      containers:
        - name: web-api-command
          image: datasynchroacr.azurecr.io/web-api-command:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5000
            - name: ASPNETCORE_ENVIRONMENT
              value: Kubernetes
            - name: ServiceBusNamespace
              value: sb-namespace-datasynchro.servicebus.windows.net
            - name: ServiceBusQueueName
              value: sb-queue-datasynchro
            - name: allowedOrigins
              value : http://aeevdzcjeshjc7cy.fz55.alb.azure.com # web app  IP
            # Reference the ConfigMap for non-sensitive connection details
            - name: SQL_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mssql-config
                  key: SQL_SERVER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mssql-config
                  key: DB_NAME
            - name: USER_NAME
              valueFrom:
                configMapKeyRef:
                  name: mssql-config
                  key: USER_NAME
            # Reference the Secret for the password
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: DB_PASSWORD
            - name: ConnectionStrings__SpeechDB
              value: "Data Source=$(SQL_SERVER);Initial Catalog=$(DB_NAME);User=$(USER_NAME);Password=$(DB_PASSWORD)"
---
apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  namespace: azure-workloads
  labels:
    app: webapi

spec:
  selector:
    app: webapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP

