apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 8051abc7-2d5c-4935-ad0a-9e2103af553e # "${USER_ASSIGNED_CLIENT_ID}"
  name: workload-identity-sa #"${SERVICE_ACCOUNT_NAME}"
  namespace: azure-workloads #"${SERVICE_ACCOUNT_NAMESPACE}"