# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  secretObjects:
  - data:
    - key: dbpassword
      objectName: dbpassword
    secretName: dbpassword
    type: Opaque 
    
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: 7c819af3-6709-4291-9bce-4a960e815de4   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: kv-shared-edusync-dev        # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: dbpassword
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: logcorner-datasync-cert
          objectType: cert                # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
       
      
    tenantId: f12a747a-cddf-4426-96ff-ebe055e215a3                 # The tenant ID of the key vault

