# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.providerClass.secret.providerClassName }}
spec:
  provider: azure
  secretObjects:
  - data:
    - key: {{ .Values.providerClass.secret.secretName }}
      objectName: {{ .Values.providerClass.secret.secretName }}
    secretName: {{  .Values.providerClass.secret.secretName }}
    type: Opaque 
    
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: {{ .Values.global.userAssignedIdentityID }}   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: {{ .Values.keyvaultName }}            # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: {{  .Values.providerClass.secret.secretName }}
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: {{ .Values.certificateName }}  
          objectType: cert                # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
       
      
    tenantId: {{ .Values.global.tenantId }}                 # The tenant ID of the key vault

