namespace: azure-workloads
serviceAccountName: workload-identity-sa
azureWorkloadIdentityClientId: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

applicationGatewayForContainerResourceId: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
applicationGatewayForContainerFrontEndName: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX