namespace: azure-workloads
serviceAccountName: workload-identity-sa
azureWorkloadIdentityClientId: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

applicationGatewayForContainerResourceId: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
applicationGatewayForContainerFrontEndName: datasynchro-frontend
webApplicationFirewallResourceId: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

keyvaultName: kv-datasynchro-004
secretName: logcorner-datasync-cert
tenantId: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

applicationInsights:
  connectionString:  XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX