apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-01
  namespace: {{ .Values.namespace }}
  annotations:
    alb.networking.azure.io/alb-id: {{ .Values.applicationGatewayForContainerResourceId }} # "${APPLICATION_GATEWAY_FOR_CONTAINER_RESOURCE_ID}"
spec:
  gatewayClassName: azure-alb-external
  listeners:
  - name: https-listener
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind : Secret
        group: ""
        name: {{ .Values.secretName }}
  addresses:
  - type: alb.networking.azure.io/alb-frontend
    value: {{ .Values.applicationGatewayForContainerFrontEndName }}
---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-route
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: gateway-01
  hostnames:
    - app.cloud-devops-craft.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /webapp/
      backendRefs:
        - name: webapp-service
          namespace: {{ .Values.namespace }}
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /signalr/
      backendRefs:
        - name: signalr-service
          namespace: {{ .Values.namespace }}
          port: 80

---
# apiVersion: alb.networking.azure.io/v1
# kind: WebApplicationFirewallPolicy
# metadata:
#   name: appgwc-waf-policy
#   namespace: {{ .Values.namespace }}
# spec:
#   targetRef:
#     group: gateway.networking.k8s.io
#     kind: HTTPRoute
#     name: http-route
#     namespace: {{ .Values.namespace }}
#   webApplicationFirewall:
#     id: {{ .Values.webApplicationFirewallResourceId }}