apiVersion: v1
kind: Namespace
metadata:
  name: azure-workloads

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 6b7ff166-a810-4d74-827c-05a90598e7e2 # "${USER_ASSIGNED_CLIENT_ID}"
  name: workload-identity-sa #"${SERVICE_ACCOUNT_NAME}"
  namespace: azure-workloads #"${SERVICE_ACCOUNT_NAMESPACE}"
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  namespace: azure-workloads
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ["/bin/sh", "-c", "sleep 3600"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    # Using sleep to keep the pod alive for testing
  restartPolicy: Always
