
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-provider-class # needs to be unique per namespace
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  secretObjects:                            # secretObjects defines the desired state of synced K8s secret objects
    - secretName:  {{ .Values.secretName }}
      type: kubernetes.io/tls
      data: 
        - objectName: {{ .Values.secretName }}
          key: tls.key
        - objectName: {{ .Values.secretName }}
          key: tls.crt
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.azureWorkloadIdentityClientId }} # Setting this to use workload identity
    keyvaultName: {{ .Values.keyvaultName }}    # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: {{ .Values.secretName }}             # Set to the name of your secret
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: "{{ .Values.tenantId }}"        # The tenant ID of the key vault