
# apiVersion: v1
# kind: Secret
# metadata:
#   name: appinsights-conn
#   namespace: monitoring
# type: Opaque
# stringData:
#   APPLICATIONINSIGHTS_CONNECTION_STRING: {{ .Values.applicationInsights.connectionString | quote }}
