

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{ .Values.azureWorkloadIdentityClientId }} # "${USER_ASSIGNED_CLIENT_ID}"
  name: workload-identity-sa #"${SERVICE_ACCOUNT_NAME}"
  namespace: azure-workloads #"${SERVICE_ACCOUNT_NAMESPACE}"